// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bmpahscihwojocyoqhjy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJtcGFoc2NpaHdvam9jeW9xaGp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAwNDAwODcsImV4cCI6MjA3NTYxNjA4N30.D-_2ciDLMlL6fzVNd-CastD1D7UuFGcIBwzeRjHHCRY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});