// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qlsipnaeaxymycrdnwno.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFsc2lwbmFlYXh5bXljcmRud25vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk4ODc2MjAsImV4cCI6MjA3NTQ2MzYyMH0.p4Z13Q9f7P7lzB-wZIDY6zYy7p2L90MouIkxKP9WAIQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});